server:
  port: 2002
spring:
  application:
    name: rabbit-boot
  rabbitmq:
    template:
      # 使用return-callback时必须设置mandatory为true
      mandatory: true
    # 消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    # 消息发送到交换机确认机制，是否返回回调
    publisher-returns: true
    listener:
      direct:
        # 确认模式设置为手动签收
        acknowledge-mode: manual
      simple:
        # 并发消费者初始化值
        concurrency: 5
        # 最大值
        max-concurrency: 10
        # 每个消费者每次监听时可拉取处理的消息数量
        prefetch: 20
    host: 101.132.110.63
    username: guest
    password: guest
